Importar librerias

In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

In [27]:
# Cargar el archivo CSV
df = pd.read_csv('datos_filtrados.csv', encoding='ISO-8859-1', on_bad_lines='skip', delimiter=',')

# Ver las primeras filas del DataFrame
df.head()

,Unnamed: 0,bathrooms,bedrooms,has_photo,price,square_feet,address,cityname,state,latitude,...,TV,Tennis,View,Washer Dryer,Wood Floors,noamenities,Cats,"Cats,Dogs",Dogs,petsunknown
0,2,1.0,0.0,1,1390,107,addressunknown,Arlington,VA,38.8910,...,0,0,0,0,0,1,0,0,0,1
1,3,1.0,0.0,1,925,116,1717 12th Avenue,Seattle,WA,47.6160,...,0,0,0,0,0,1,0,0,0,1
2,5,1.0,0.0,1,2475,130,350 West 50th St,Manhattan,NY,40.7629,...,0,0,0,0,0,0,0,0,0,1
3,8,1.0,0.0,1,1495,138,333 Hyde St,San Francisco,CA,37.7599,...,0,0,0,0,0,0,0,0,0,1
4,14,1.0,0.0,1,1695,190,57 Taylor St,San Francisco,CA,37.7599,...,0,0,0,0,0,0,0,0,0,1

In [28]:
print(sorted(df["state"].unique()))

['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']

In [29]:
Variable_interes=["price"]

y=df[Variable_interes]

Variables_influyentes = df.columns.tolist()
Variables_influyentes.remove("price")
Variables_influyentes.remove("Unnamed: 0")
Variables_influyentes.remove("address")
Variables_influyentes.remove("cityname")
Variables_influyentes.remove("latitude")
Variables_influyentes.remove("longitude")
Variables_influyentes.remove("source")
Variables_influyentes.remove("time")
Variables_influyentes.remove("petsunknown")
Variables_influyentes.remove("noamenities")



x=df[Variables_influyentes]

#Generar dummies
x = pd.get_dummies(x, drop_first=True).astype(float)

x.head()

,bathrooms,bedrooms,has_photo,square_feet,AC,Alarm,Basketball,Cable or Satellite,Clubhouse,Dishwasher,...,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
0,1.0,0.0,1.0,107.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,116.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,1.0,130.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,190.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
x.shape[1] - 34

50

Análisis Estadístico

In [31]:
x = sm.add_constant(x)
x

,bathrooms,bedrooms,has_photo,square_feet,AC,Alarm,Basketball,Cable or Satellite,Clubhouse,Dishwasher,...,state_SD,state_TN,state_TX,state_UT,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY
0,1.0,0.0,1.0,107.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,116.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,1.0,130.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,138.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,190.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9269,4.0,5.0,1.0,3966.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9270,3.5,5.0,1.0,4000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9271,4.5,4.0,1.0,4500.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9272,3.5,5.0,1.0,4614.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9273,1.0,1.0,1.0,880.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
An = sm.OLS(y, x)  # Crea el modelo
results = An.fit()

In [33]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.589
Model:                            OLS   Adj. R-squared:                  0.585
Method:                 Least Squares   F-statistic:                     158.4
Date:               lu., 24 feb. 2025   Prob (F-statistic):               0.00
Time:                        15:15:37   Log-Likelihood:                -66663.
No. Observations:                9274   AIC:                         1.335e+05
Df Residuals:                    9190   BIC:                         1.341e+05
Df Model:                          83
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
bathrooms            120.3270     10.127     11.881      0.000     100.475     140.179
bedrooms              16.3629      5.990      2.732      0.006       4.621      28.105
has_photo            479.6369     50.018      9.589      0.000     381.590     577.683
square_feet            0.4382      0.014     31.528      0.000       0.411       0.465
AC                   -81.2094     15.879     -5.114      0.000    -112.336     -50.082
Alarm                  1.1835     72.752      0.016      0.987    -141.427     143.793
Basketball           -74.9840     20.248     -3.703      0.000    -114.675     -35.293
Cable or Satellite   -51.3753     13.178     -3.899      0.000     -77.206     -25.544
Clubhouse             10.9589     11.991      0.914      0.361     -12.547      34.465
Dishwasher            18.3526     11.055      1.660      0.097      -3.318      40.023
Doorman               53.0253     66.003      0.803      0.422     -76.355     182.406
Elevator             191.8236     15.253     12.576      0.000     161.925     221.722
Fireplace            -30.5279     12.096     -2.524      0.012     -54.239      -6.817
Garbage Disposal     -55.0388     13.109     -4.198      0.000     -80.736     -29.342
Gated                  0.2251     16.713      0.013      0.989     -32.537      32.987
Golf                  80.1601     69.567      1.152      0.249     -56.206     216.526
Gym                   70.0405     12.330      5.681      0.000      45.871      94.209
Hot Tub               38.1196     19.567      1.948      0.051      -0.235      76.474
Internet Access       64.0344     12.834      4.989      0.000      38.877      89.192
Luxury               135.2352    102.145      1.324      0.186     -64.992     335.462
Parking               39.7779      8.413      4.728      0.000      23.286      56.270
Patio/Deck            -8.8497      9.899     -0.894      0.371     -28.253      10.554
Playground          -143.1334     13.745    -10.413      0.000    -170.077    -116.189
Pool                  11.2032      9.249      1.211      0.226      -6.928      29.334
Refrigerator         -59.2492     11.851     -4.999      0.000     -82.480     -36.018
Storage               -1.8437     10.359     -0.178      0.859     -22.150      18.462
TV                    62.9220     23.923      2.630      0.009      16.027     109.817
Tennis               -57.4413     17.167     -3.346      0.001     -91.092     -23.790
View                  75.9991     28.810      2.638      0.008      19.526     132.473
Washer Dryer          -8.2887     13.270     -0.625      0.532     -34.301      17.724
Wood Floors           94.5582     18.986      4.981      0.000      57.342     131.774
Cats                  11.3514     16.565      0.685      0.493     -21.119      43.822
Cats,Dogs             48.9369      7.537      6.492      0.000      34.162      63.712
Dogs                 100.0649     32.919      3.040      0.002      35.537     164.593
state_AL             -67.9605     65.830     -1.032      0.302    -197.002      61.081
state_AR            -264.0062     65.715     -4.017      0.000    -392.822    -135.191
state_AZ              12.8461     57.332      0.224      0.823     -99.536     125.229
state_CA             962.2126     50.887     18.909      0.000     862.463    1061.962
state_CO             263.1197     52.618      5.001      0.000     159.976     366.263
state_CT             233.4427     59.387      3.931      0.000     117.032     349.853
state_DC             999.8625     64.668     15.461      0.000     873.098    1126.627
state_DE              83.0882    152.197      0.546      0.585    -215.251     381.427
state_FL             214.0567     52.670      4.064      0.000     110.812     317.302
state_GA              58.6738     52.253      1.123      0.262     -43.754     161.101
state_HI            1040.9492    140.309      7.419      0.000     765.912    1315.986
state_IA            -136.5842     54.798     -2.493      0.013    -244.000     -29.169
state_ID             185.5763     85.802      2.163      0.031      17.385     353.768
state_IL             275.3759     52.796      5.216      0.000     171.885     378.867
state_IN             -47.8020     53.924     -0.886      0.375    -153.505      57.901
state_KS            -139.9461     60.914     -2.297      0.022    -259.351     -20.541
state_KY            -135.2049     71.249     -1.898      0.058    -274.870       4.460
state_LA            -112.1329     63.248     -1.773      0.076    -236.114      11.848
state_MA             928.8285     57.070     16.275      0.000     816.959    1040.698
state_MD             435.2212     52.052      8.361      0.000     333.187     537.255
state_ME             719.1677    232.930      3.087      0.002     262.574    1175.762
state_MI               7.0817     55.404      0.128      0.898    -101.522     115.685
state_MN             267.2974     54.065      4.944      0.000     161.319     373.276
state_MO             -75.2060     53.586     -1.403      0.161    -180.247      29.835
state_MS            -267.5823    118.427     -2.259      0.024    -499.726     -35.439
state_MT             135.6718    140.881      0.963      0.336    -140.485     411.829
state_NC             -45.6406     51.828     -0.881      0.379    -147.235      55.954
state_ND            -218.2554     57.869     -3.772      0.000    -331.692    -104.819
state_NE            -106.2386     58.339     -1.821      0.069    -220.596       8.119
state_NH             379.5941     62.936      6.031      0.000     256.225     502.963
state_NJ             680.0400     52.684     12.908      0.000     576.768     783.312
state_NM             -12.9227     99.072     -0.130      0.896    -207.126     181.280
state_NV              63.1039     57.787      1.092      0.275     -50.172     176.380
state_NY             413.4740     63.988      6.462      0.000     288.043     538.905
state_OH             -56.4848     52.587     -1.074      0.283    -159.566      46.597
state_OK            -161.8707     55.079     -2.939      0.003    -269.838     -53.903
state_OR             342.7319     54.632      6.273      0.000     235.642     449.822
state_PA             193.6285     54.875      3.529      0.000      86.061     301.196
state_RI             357.9959    114.455      3.128      0.002     133.639     582.353
state_SC            -103.6756     61.699     -1.680      0.093    -224.620      17.269
state_SD            -207.9110     63.135     -3.293      0.001    -331.670     -84.152
state_TN             171.8348     59.925      2.867      0.004      54.368     289.302
state_TX              93.7050     49.758      1.883      0.060      -3.832     191.242
state_UT              78.7976     60.750      1.297      0.195     -40.285     197.880
state_VA             290.7810     54.235      5.362      0.000     184.469     397.093
state_VT             298.7967     94.592      3.159      0.002     113.376     484.217
state_WA             577.0581     51.329     11.242      0.000     476.442     677.674
state_WI             148.4553     53.083      2.797      0.005      44.400     252.511
state_WV            -341.0952    192.617     -1.771      0.077    -718.667      36.476
state_WY            -669.1618    325.664     -2.055      0.040   -1307.536     -30.788
==============================================================================
Omnibus:                      764.644   Durbin-Watson:                   1.493
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1392.546
Skew:                           0.585   Prob(JB):                    4.10e-303
Kurtosis:                       4.495   Cond. No.                     1.10e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [34]:
# Get p-values from the results
p_values = results.pvalues

# Filter variables with p-value greater than 0.07
non_significant_vars = p_values[p_values > 0.07].index.tolist()

print("Variables no significativas:", non_significant_vars)

Variables no significativas: ['Alarm', 'Clubhouse', 'Dishwasher', 'Doorman', 'Gated', 'Golf', 'Luxury', 'Patio/Deck', 'Pool', 'Storage', 'Washer Dryer', 'Cats', 'state_AL', 'state_AZ', 'state_DE', 'state_GA', 'state_IN', 'state_LA', 'state_MI', 'state_MO', 'state_MT', 'state_NC', 'state_NM', 'state_NV', 'state_OH', 'state_SC', 'state_UT', 'state_WV']

In [35]:
for i in non_significant_vars[:10]:
    Variables_influyentes.remove(i)

In [36]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Supongamos que tienes un DataFrame con columnas 'feature1' y 'feature2'
df['baños*area'] = df['bathrooms'] * df['square_feet']
df['cuartos*area'] = df['bedrooms'] * df['square_feet']
df['cuartos*baños'] = df['bedrooms'] * df['bathrooms']

In [37]:
Variables_influyentes.append('baños*area')
Variables_influyentes.append('cuartos*area')
Variables_influyentes.append('cuartos*baños')

x=df[Variables_influyentes]

#Generar dummies
x = pd.get_dummies(x, drop_first=True).astype(float)

x = sm.add_constant(x)

An = sm.OLS(y, x)  # Crea el modelo
results = An.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.590
Method:                 Least Squares   F-statistic:                     176.7
Date:               lu., 24 feb. 2025   Prob (F-statistic):               0.00
Time:                        15:15:38   Log-Likelihood:                -66608.
No. Observations:                9274   AIC:                         1.334e+05
Df Residuals:                    9197   BIC:                         1.339e+05
Df Model:                          76
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
bathrooms             37.2659     27.752      1.343      0.179     -17.134      91.666
bedrooms              15.2053     14.238      1.068      0.286     -12.704      43.115
has_photo            409.3351     53.401      7.665      0.000     304.657     514.013
square_feet            0.7547      0.034     22.484      0.000       0.689       0.820
AC                   -81.5519     15.526     -5.253      0.000    -111.986     -51.118
Basketball           -73.3532     20.086     -3.652      0.000    -112.726     -33.980
Cable or Satellite   -44.9453     12.984     -3.462      0.001     -70.396     -19.495
Elevator             198.5760     15.062     13.184      0.000     169.051     228.101
Fireplace            -29.9162     11.777     -2.540      0.011     -53.001      -6.831
Garbage Disposal     -55.3365     12.554     -4.408      0.000     -79.946     -30.727
Gym                   67.5268     11.437      5.904      0.000      45.107      89.946
Hot Tub               41.4301     19.133      2.165      0.030       3.926      78.934
Internet Access       66.4681     12.639      5.259      0.000      41.694      91.242
Parking               38.9269      8.017      4.855      0.000      23.211      54.643
Playground          -142.8787     13.403    -10.660      0.000    -169.152    -116.606
Refrigerator         -48.3626     10.141     -4.769      0.000     -68.241     -28.484
TV                    58.7330     23.744      2.474      0.013      12.189     105.277
Tennis               -56.7779     16.917     -3.356      0.001     -89.938     -23.617
View                  76.8785     28.399      2.707      0.007      21.211     132.546
Washer Dryer         -15.5334     13.109     -1.185      0.236     -41.229      10.162
Wood Floors           93.4292     18.789      4.973      0.000      56.599     130.259
Cats                   7.5779     16.432      0.461      0.645     -24.632      39.788
Cats,Dogs             45.4110      7.466      6.083      0.000      30.777      60.045
Dogs                 106.6157     32.707      3.260      0.001      42.503     170.728
baños*area            -0.0515      0.015     -3.361      0.001      -0.082      -0.021
cuartos*area          -0.0851      0.011     -7.523      0.000      -0.107      -0.063
cuartos*baños         58.3892     10.947      5.334      0.000      36.930      79.848
state_AL            -101.1420     65.068     -1.554      0.120    -228.690      26.406
state_AR            -292.8750     64.983     -4.507      0.000    -420.255    -165.495
state_AZ              10.3620     56.465      0.184      0.854    -100.323     121.047
state_CA             946.0728     50.098     18.885      0.000     847.870    1044.276
state_CO             252.2816     51.774      4.873      0.000     150.793     353.770
state_CT             210.6296     58.494      3.601      0.000      95.968     325.291
state_DC             995.4483     63.921     15.573      0.000     870.150    1120.747
state_DE              78.5035    151.081      0.520      0.603    -217.648     374.655
state_FL             199.1792     51.792      3.846      0.000      97.656     300.702
state_GA              33.8987     51.499      0.658      0.510     -67.050     134.847
state_HI            1019.2942    139.267      7.319      0.000     746.300    1292.289
state_IA            -164.4145     54.071     -3.041      0.002    -270.406     -58.423
state_ID             163.0999     85.051      1.918      0.055      -3.619     329.819
state_IL             259.2109     52.273      4.959      0.000     156.745     361.677
state_IN             -71.3522     53.280     -1.339      0.181    -175.792      33.088
state_KS            -163.7440     60.139     -2.723      0.006    -281.630     -45.858
state_KY            -154.3712     70.560     -2.188      0.029    -292.685     -16.057
state_LA            -142.4288     62.476     -2.280      0.023    -264.896     -19.962
state_MA             901.9149     56.299     16.020      0.000     791.556    1012.274
state_MD             408.8562     51.232      7.981      0.000     308.430     509.282
state_ME             669.0464    231.391      2.891      0.004     215.468    1122.625
state_MI             -14.3392     54.702     -0.262      0.793    -121.568      92.889
state_MN             242.6359     53.435      4.541      0.000     137.891     347.381
state_MO            -100.1065     52.917     -1.892      0.059    -203.836       3.623
state_MS            -302.3209    117.275     -2.578      0.010    -532.206     -72.436
state_MT             100.6721    139.843      0.720      0.472    -173.451     374.795
state_NC             -71.7448     51.051     -1.405      0.160    -171.816      28.326
state_ND            -253.9670     57.120     -4.446      0.000    -365.935    -141.999
state_NE            -134.8397     57.629     -2.340      0.019    -247.806     -21.874
state_NH             353.7442     62.210      5.686      0.000     231.798     475.690
state_NJ             649.9974     51.910     12.522      0.000     548.241     751.753
state_NM             -33.1511     98.190     -0.338      0.736    -225.626     159.324
state_NV              39.9666     56.994      0.701      0.483     -71.754     151.687
state_NY             384.8773     63.341      6.076      0.000     260.714     509.040
state_OH             -86.8056     51.884     -1.673      0.094    -188.510      14.899
state_OK            -188.0998     54.264     -3.466      0.001    -294.468     -81.731
state_OR             328.9486     53.861      6.107      0.000     223.368     434.529
state_PA             165.4649     54.107      3.058      0.002      59.402     271.528
state_RI             330.7826    113.179      2.923      0.003     108.926     552.639
state_SC            -111.1245     61.073     -1.820      0.069    -230.842       8.593
state_SD            -243.4626     62.492     -3.896      0.000    -365.962    -120.964
state_TN             152.2788     59.207      2.572      0.010      36.221     268.337
state_TX              79.8888     49.070      1.628      0.104     -16.299     176.077
state_UT              65.7536     59.994      1.096      0.273     -51.849     183.356
state_VA             280.0982     53.479      5.238      0.000     175.268     384.929
state_VT             246.9117     93.749      2.634      0.008      63.143     430.681
state_WA             556.3028     50.631     10.987      0.000     457.056     655.550
state_WI             117.6413     52.340      2.248      0.025      15.044     220.239
state_WV            -262.7768    191.561     -1.372      0.170    -638.280     112.726
state_WY            -725.0175    323.565     -2.241      0.025   -1359.278     -90.757
==============================================================================
Omnibus:                      741.916   Durbin-Watson:                   1.517
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1372.919
Skew:                           0.566   Prob(JB):                    7.49e-299
Kurtosis:                       4.507   Cond. No.                     3.69e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.69e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [38]:
results.params.tolist()

[37.265936251306286,
 15.205326003594978,
 409.33508381703854,
 0.7546500388516394,
 -81.55191855790758,
 -73.35316282352778,
 -44.94527730470488,
 198.57599052326992,
 -29.91615975310512,
 -55.33648359426826,
 67.52681899907412,
 41.430104786120275,
 66.46807394537436,
 38.92694119532015,
 -142.87871781450204,
 -48.36258847798169,
 58.73299801125381,
 -56.7778997614422,
 76.87847834192901,
 -15.533353126466213,
 93.42923716857075,
 7.57788355287299,
 45.41098787338171,
 106.61571049539543,
 -0.051517627964306735,
 -0.0851364458706164,
 58.389154510423374,
 -101.14196459331819,
 -292.87495854219577,
 10.361984934813634,
 946.0728327166694,
 252.28157484171948,
 210.6295534433365,
 995.4483444340941,
 78.50352782641835,
 199.1792133001659,
 33.89874732801181,
 1019.2942314898675,
 -164.41451539665636,
 163.09993258445095,
 259.21089264524903,
 -71.35220008817164,
 -163.74399956451649,
 -154.371183804003,
 -142.4288221171675,
 901.9149210951749,
 408.856156485431,
 669.046375762937,
 -14.339158073837131,
 242.6358709704696,
 -100.10645439978887,
 -302.32086836805763,
 100.67209052365256,
 -71.74483502762583,
 -253.96697753351737,
 -134.83974510625964,
 353.744180417779,
 649.9974341869424,
 -33.151122559095164,
 39.966578823276436,
 384.8773409019981,
 -86.80555301299188,
 -188.0997884528792,
 328.948563184701,
 165.46489231377677,
 330.78260636473954,
 -111.1245426746746,
 -243.46264683463127,
 152.2787682778554,
 79.88884990983723,
 65.75361108843241,
 280.0981804462247,
 246.9116998602925,
 556.3028012599361,
 117.64129286330245,
 -262.77684564694863,
 -725.0175030551809]

In [39]:
# disntacia de Cook
resultados_cooksd = results.get_influence().cooks_distance[0]

# get length of df to obtain n
n = x.shape[0]

# umbral
critical_d = 4/n
print('Umbral con distancia de Cook:', critical_d)

# puntos que podrían ser ourliers con alta influencia
out_d = resultados_cooksd > critical_d

print(x.index[out_d], "\n", resultados_cooksd[out_d])

Umbral con distancia de Cook: 0.00043131334914815614
Index([   2,    5,    6,   14,  188,  190,  193,  210,  227,  238,
       ...
       9257, 9258, 9259, 9260, 9263, 9264, 9266, 9268, 9269, 9271],
      dtype='int64', length=448)
 [0.00519962 0.00160384 0.00160384 0.00548184 0.00049546 0.00122444
 0.0005787  0.00158464 0.00058915 0.00136588 0.0004897  0.00067421
 0.0004977  0.00046684 0.00836899 0.00058215 0.00131629 0.00045273
 0.00527093 0.0010187  0.00052938 0.00045535 0.00062843 0.00067043
 0.0050134  0.00063119 0.00046774 0.000436   0.00139564 0.00081539
 0.00112421 0.00073677 0.00073251 0.00126582 0.0010023  0.00070378
 0.00164463 0.00065804 0.00055089 0.00152261 0.00059861 0.00069396
 0.00063161 0.00107681 0.0008004  0.00045595 0.00119512 0.00081229
 0.00049335 0.00260282 0.00237291 0.00239136 0.00080787 0.00063244
 0.00067742 0.00049456 0.00147818 0.00137837 0.0006336  0.00070181
 0.00061058 0.00046806 0.00067581 0.00103297 0.00054594 0.00065691
 0.00059338 0.00044731 0.00079008 0.00075774 0.00117226 0.00189255
 0.00074168 0.00192446 0.00066277 0.00125104 0.00135501 0.00057121
 0.00073781 0.00049032 0.00070102 0.00083122 0.00092899 0.00046001
 0.00090192 0.00043412 0.0006537  0.00204188 0.00045733 0.00066194
 0.00105153 0.00195721 0.00055024 0.00186634 0.00430508 0.00140306
 0.0016721  0.00055115 0.00045851 0.00252854 0.00044083 0.00248395
 0.00064404 0.00125215 0.00126848 0.00088815 0.0009429  0.00060436
 0.0006494  0.00081598 0.00140967 0.00347802 0.00092876 0.001607
 0.00125799 0.00043431 0.03130066 0.00044677 0.00047974 0.00050562
 0.00170563 0.0013531  0.00181783 0.00062557 0.00064284 0.00051981
 0.00139638 0.00053398 0.00044355 0.00046072 0.0004435  0.00044806
 0.00271316 0.00162343 0.00140092 0.00046249 0.00085886 0.00048602
 0.00159583 0.00059355 0.00173839 0.00077016 0.00091691 0.00133903
 0.00050924 0.00067358 0.00048892 0.00176751 0.00065231 0.00180818
 0.00104181 0.0011268  0.0005068  0.00056163 0.0004692  0.00077306
 0.00133475 0.000874   0.00063667 0.00067961 0.00094094 0.00842687
 0.00045762 0.00052724 0.00069515 0.00070151 0.00048622 0.00048264
 0.00045167 0.00072841 0.00076223 0.00043431 0.00044878 0.00046594
 0.0007418  0.00058717 0.00051219 0.00299262 0.00055735 0.00044901
 0.00085695 0.00056026 0.00313384 0.00043423 0.0009509  0.00045264
 0.00051081 0.0054893  0.00052773 0.00079781 0.00070447 0.00064633
 0.00044346 0.00082392 0.0011044  0.00083928 0.00142972 0.00050188
 0.00351118 0.00067725 0.00048159 0.00090512 0.00073761 0.00083244
 0.00068651 0.00064796 0.00078449 0.00052994 0.00233629 0.00128404
 0.00043835 0.00055857 0.0031863  0.00043974 0.00085467 0.0004542
 0.00066377 0.00050582 0.00086048 0.00189716 0.00127096 0.00073873
 0.00071829 0.00047303 0.00048498 0.00053772 0.00131433 0.00151512
 0.00047393 0.00262524 0.00064652 0.00056379 0.00074774 0.0005253
 0.00120121 0.00064777 0.00151896 0.00212274 0.00071046 0.00098748
 0.00103367 0.00056228 0.00065687 0.00052248 0.00062764 0.00081676
 0.00091492 0.0004639  0.0020669  0.00102968 0.00054296 0.00054089
 0.00085816 0.00043621 0.00099354 0.00046301 0.00097373 0.00043576
 0.0005211  0.00047816 0.00141343 0.00062845 0.00079661 0.00054287
 0.00057755 0.00062996 0.00057539 0.00110611 0.00048248 0.00048248
 0.00055381 0.00087812 0.00045354 0.0004992  0.00080115 0.0006538
 0.00147414 0.00088226 0.00122735 0.00086813 0.00111531 0.00075624
 0.00077722 0.00103836 0.00071988 0.00171888 0.00057654 0.0012477
 0.00096543 0.00046409 0.00113627 0.00052452 0.00060254 0.00044809
 0.0005662  0.00102378 0.00122344 0.00097429 0.00044331 0.00067124
 0.00067124 0.00144071 0.00072799 0.00122516 0.00052095 0.00052095
 0.0004349  0.00126898 0.00071173 0.00065998 0.00063365 0.00120397
 0.00339667 0.00479192 0.00058338 0.00045726 0.00111549 0.00066297
 0.00050504 0.0004642  0.00750972 0.00070406 0.00044789 0.0005497
 0.00139421 0.00073713 0.00073713 0.00162298 0.0005834  0.00071127
 0.00077815 0.00099277 0.00120794 0.00189657 0.00282282 0.03130066
 0.00046741 0.00072407 0.00067093 0.00045766 0.00076273 0.00264826
 0.00087833 0.00059464 0.00065576 0.00044182 0.00047996 0.00067823
 0.00410704 0.00054319 0.00237214 0.00099194 0.0015284  0.00049968
 0.00110233 0.00363397 0.00044758 0.00053837 0.00067668 0.00095196
 0.00095196 0.00184616 0.00048045 0.00176735 0.00115289 0.00149405
 0.00140382 0.00346709 0.00077391 0.00086118 0.00090724 0.000672
 0.00144433 0.00137102 0.00096613 0.00047993 0.00569072 0.00107761
 0.00139067 0.00184799 0.00179842 0.0023016  0.00050289 0.00189466
 0.00091959 0.00049646 0.00054607 0.00130296 0.00276872 0.00250974
 0.00045582 0.00090042 0.00072151 0.00076108 0.00065957 0.00176225
 0.00107829 0.00051808 0.00047561 0.00315813 0.00337177 0.00048755
 0.00048755 0.0018212  0.00094866 0.00080336 0.00186651 0.00542846
 0.00158008 0.00047827 0.00060755 0.00050149 0.00079814 0.00115515
 0.001396   0.00050473 0.00072306 0.00269441 0.00075588 0.00080063
 0.00052206 0.0011238  0.00067948 0.0015418  0.0013453  0.00115159
 0.00062251 0.00047548 0.00051526 0.00082122 0.0004687  0.00047395
 0.00097135 0.00083277 0.0011176  0.00082508 0.00063341 0.00190881
 0.0005652  0.00084931 0.00167588 0.00049275 0.00053192 0.00158448
 0.00057823 0.00082968 0.00128641 0.00157734]

c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\outliers_influence.py:847: RuntimeWarning: invalid value encountered in sqrt
  return self.resid / sigma / np.sqrt(1 - hii)

In [40]:
import pandas as pd

#Remover los outliers influyentes

indices_a_remover = x.index[out_d].tolist()  

df = df.drop(indices_a_remover)

In [41]:
x=df[Variables_influyentes]

#Generar dummies
x = pd.get_dummies(x, drop_first=True).astype(float)

x = sm.add_constant(x)

y=df[Variable_interes]
An = sm.OLS(y, x)  # Crea el modelo
results = An.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.662
Model:                            OLS   Adj. R-squared:                  0.660
Method:                 Least Squares   F-statistic:                     228.9
Date:               lu., 24 feb. 2025   Prob (F-statistic):               0.00
Time:                        15:15:38   Log-Likelihood:                -62073.
No. Observations:                8826   AIC:                         1.243e+05
Df Residuals:                    8750   BIC:                         1.248e+05
Df Model:                          75
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
bathrooms            -33.5170     26.888     -1.247      0.213     -86.224      19.190
bedrooms              13.9754     13.750      1.016      0.309     -12.979      40.929
has_photo            420.8010     47.559      8.848      0.000     327.573     514.029
square_feet            0.8114      0.032     25.374      0.000       0.749       0.874
AC                   -91.1693     13.872     -6.572      0.000    -118.361     -63.977
Basketball           -42.5176     17.928     -2.372      0.018     -77.660      -7.375
Cable or Satellite   -45.8999     11.495     -3.993      0.000     -68.432     -23.368
Elevator             194.7076     13.465     14.460      0.000     168.313     221.102
Fireplace            -33.3188     10.338     -3.223      0.001     -53.584     -13.053
Garbage Disposal     -49.7193     11.082     -4.486      0.000     -71.443     -27.995
Gym                   72.0563     10.036      7.180      0.000      52.383      91.730
Hot Tub               31.8646     16.955      1.879      0.060      -1.370      65.100
Internet Access       69.9098     11.194      6.245      0.000      47.966      91.853
Parking               40.3612      7.066      5.712      0.000      26.511      54.211
Playground          -139.0217     11.729    -11.853      0.000    -162.013    -116.030
Refrigerator         -53.3375      9.030     -5.907      0.000     -71.038     -35.637
TV                    29.0150     21.338      1.360      0.174     -12.813      70.843
Tennis               -51.9960     14.954     -3.477      0.001     -81.308     -22.684
View                  62.4687     25.750      2.426      0.015      11.994     112.944
Washer Dryer          -8.4168     11.612     -0.725      0.469     -31.179      14.345
Wood Floors           74.6128     17.073      4.370      0.000      41.146     108.079
Cats                  23.8258     14.594      1.633      0.103      -4.782      52.434
Cats,Dogs             52.5642      6.616      7.945      0.000      39.595      65.534
Dogs                 101.0075     32.087      3.148      0.002      38.109     163.906
baños*area            -0.0267      0.016     -1.626      0.104      -0.059       0.005
cuartos*area          -0.1151      0.011    -10.443      0.000      -0.137      -0.093
cuartos*baños         73.9894     10.942      6.762      0.000      52.540      95.438
state_AL            -123.2324     60.477     -2.038      0.042    -241.781      -4.684
state_AR            -302.2066     57.315     -5.273      0.000    -414.558    -189.855
state_AZ               7.8451     49.236      0.159      0.873     -88.668     104.358
state_CA             970.7026     43.690     22.218      0.000     885.060    1056.346
state_CO             255.1742     45.135      5.654      0.000     166.698     343.650
state_CT             166.9932     51.631      3.234      0.001      65.784     268.202
state_DC            1003.9541     56.728     17.698      0.000     892.753    1115.155
state_DE             112.3498    278.762      0.403      0.687    -434.089     658.788
state_FL             192.4845     45.185      4.260      0.000     103.912     281.057
state_GA              23.3533     44.921      0.520      0.603     -64.703     111.409
state_HI            1011.3820    144.117      7.018      0.000     728.878    1293.886
state_IA            -164.0062     47.098     -3.482      0.000    -256.329     -71.683
state_ID             130.1136     97.061      1.341      0.180     -60.148     320.375
state_IL             234.8462     45.674      5.142      0.000     145.314     324.379
state_IN             -89.1538     46.500     -1.917      0.055    -180.306       1.998
state_KS            -177.6644     53.062     -3.348      0.001    -281.678     -73.651
state_KY            -207.6825     64.518     -3.219      0.001    -334.152     -81.213
state_LA            -181.2986     55.458     -3.269      0.001    -290.010     -72.587
state_MA             911.1755     51.471     17.703      0.000     810.280    1012.071
state_MD             409.2531     44.652      9.165      0.000     321.725     496.781
state_MI             -66.4984     48.019     -1.385      0.166    -160.628      27.631
state_MN             226.2443     46.649      4.850      0.000     134.802     317.687
state_MO            -121.6256     46.223     -2.631      0.009    -212.234     -31.017
state_MS            -334.4948    199.561     -1.676      0.094    -725.681      56.691
state_MT              19.3201    200.077      0.097      0.923    -372.878     411.519
state_NC             -75.0150     44.529     -1.685      0.092    -162.302      12.272
state_ND            -251.4723     49.705     -5.059      0.000    -348.905    -154.039
state_NE            -141.4213     50.147     -2.820      0.005    -239.722     -43.121
state_NH             361.8713     54.332      6.660      0.000     255.367     468.375
state_NJ             619.2526     45.447     13.626      0.000     530.166     708.339
state_NM             -84.7727     90.003     -0.942      0.346    -261.199      91.654
state_NV              39.7192     49.613      0.801      0.423     -57.535     136.973
state_NY             268.7570     65.136      4.126      0.000     141.075     396.439
state_OH             -90.6469     45.239     -2.004      0.045    -179.326      -1.968
state_OK            -166.1029     47.315     -3.511      0.000    -258.851     -73.355
state_OR             334.9700     46.875      7.146      0.000     243.083     426.857
state_PA             172.0940     47.410      3.630      0.000      79.159     265.029
state_RI             261.1873    121.144      2.156      0.031      23.717     498.657
state_SC            -164.1901     54.313     -3.023      0.003    -270.657     -57.723
state_SD            -238.0634     54.238     -4.389      0.000    -344.382    -131.745
state_TN              -7.5350     54.934     -0.137      0.891    -115.220     100.150
state_TX              87.2201     42.780      2.039      0.041       3.362     171.078
state_UT              41.9927     52.643      0.798      0.425     -61.201     145.186
state_VA             280.2457     47.040      5.958      0.000     188.037     372.455
state_VT             349.5497    130.413      2.680      0.007      93.909     605.190
state_WA             552.2525     44.153     12.508      0.000     465.703     638.802
state_WI              90.4551     45.792      1.975      0.048       0.693     180.217
state_WV            -201.9295    280.421     -0.720      0.471    -751.620     347.761
state_WY            -713.1268    278.842     -2.557      0.011   -1259.723    -166.531
==============================================================================
Omnibus:                      371.387   Durbin-Watson:                   1.574
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              532.326
Skew:                           0.407   Prob(JB):                    2.55e-116
Kurtosis:                       3.886   Cond. No.                     3.56e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.56e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

Validación cruzada para escoger el modelo adecuado

RL

In [ ]:
from sklearn.model_selection import cross_validate
import numpy as np

model = LinearRegression()
# Evaluar múltiples métricas: MSE y R^2
scoring = ['neg_mean_squared_error', 'r2']
scores = cross_validate(model, x, y, cv=5, scoring=scoring, return_train_score=True)

# Obtener y mostrar los resultados
mse_scores_rl = -scores['test_neg_mean_squared_error']
r2_scores_rl = scores['test_r2']

print("MSE scores:", np.mean(mse_scores))
print("R^2 scores:", np.mean(r2_scores_rl))

# Calcular y mostrar RMSE
rmse_scores = np.sqrt(mse_scores)
print("RMSE scores:", rmse_scores)

MSE scores: 80140.52065525642
R^2 scores: 0.577761273255174
RMSE scores: [276.83732719 261.51704063 281.62002306 295.48119439 298.41843338]

Ridge

In [43]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

ridge_model = Ridge(alpha=1.0)
# Evaluar múltiples métricas: MSE y R^2
scoring = ['neg_mean_squared_error', 'r2']
scores = cross_validate(ridge_model, x, y, cv=5, scoring=scoring, return_train_score=True)

# Obtener y mostrar los resultados
mse_scores = -scores['test_neg_mean_squared_error']
r2_scores = scores['test_r2']

print("MSE scores:", np.mean(mse_scores))
print("R^2 scores:", np.mean(r2_scores))

# Calcular y mostrar RMSE
rmse_scores = np.sqrt(mse_scores)
print("RMSE scores:", rmse_scores)

MSE scores: 80842.87900565841
R^2 scores: 0.5740597965192848
RMSE scores: [276.04251774 261.68470522 282.05144928 295.65137612 304.25857792]

Lasso

In [44]:

lasso_model = Lasso(alpha=1.0)
# Evaluar múltiples métricas: MSE y R^2
scoring = ['neg_mean_squared_error', 'r2']
scores = cross_validate(lasso_model, x, y, cv=5, scoring=scoring, return_train_score=True)

# Obtener y mostrar los resultados
mse_scores = -scores['test_neg_mean_squared_error']
r2_scores = scores['test_r2']

print("MSE scores:", np.mean(mse_scores))
print("R^2 scores:", np.mean(r2_scores))

# Calcular y mostrar RMSE
rmse_scores = np.sqrt(mse_scores)
print("RMSE scores:", rmse_scores)

MSE scores: 86240.5916681377
R^2 scores: 0.5458064235485586
RMSE scores: [278.48529206 267.98512567 290.49478809 303.00731151 325.0111077 ]

ElasticNt

In [45]:
elastic_model = ElasticNet(alpha=1.0, l1_ratio=0.5)
# Evaluar múltiples métricas: MSE y R^2
scoring = ['neg_mean_squared_error', 'r2']
scores = cross_validate(elastic_model, x, y, cv=5, scoring=scoring, return_train_score=True)

# Obtener y mostrar los resultados
mse_scores = -scores['test_neg_mean_squared_error']
r2_scores = scores['test_r2']

print("MSE scores:", np.mean(mse_scores))
print("R^2 scores:", np.mean(r2_scores))

# Calcular y mostrar RMSE
rmse_scores = np.sqrt(mse_scores)
print("RMSE scores:", rmse_scores)

MSE scores: 171674.35182146291
R^2 scores: 0.0985682184642263
RMSE scores: [387.84284215 397.160092   421.37728617 443.38176972 419.60378835]

Random Forest

In [46]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer, r2_score
from scipy.stats import randint, uniform
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Definir el modelo de Random Forest
rf_model = RandomForestRegressor(random_state=42)

# Definir la distribución de hiperparámetros
param_dist = {
    'n_estimators': randint(100, 500),  # Número de árboles entre 100 y 500
    'max_depth': [None, 10, 20, 30],   # Profundidad máxima de los árboles
    'min_samples_split': randint(2, 11),  # Mínimo de muestras para dividir un nodo (2 a 10)
    'min_samples_leaf': randint(1, 5),    # Mínimo de muestras en una hoja (1 a 4)
    'max_features': ['sqrt', 'log2']      # Número de características a considerar en cada división
}

# Definir la métrica de evaluación (R² en este caso)
scorer = make_scorer(r2_score)

# Crear el Randomized Search
random_search = RandomizedSearchCV(
    estimator=rf_model,
    param_distributions=param_dist,
    n_iter=50,  # Número de combinaciones aleatorias a probar
    scoring=scorer,
    cv=5,  # Validación cruzada con 5 folds
    n_jobs=-1,  # Usar todos los núcleos del procesador
    random_state=42
)

# Entrenar el Randomized Search
random_search.fit(x_train, y_train)

# Mejores parámetros encontrados
best_params = random_search.best_params_
print(f'Mejores parámetros: {best_params}')

# Mejor modelo
best_rf_model = random_search.best_estimator_

# Evaluar el mejor modelo en el conjunto de prueba
y_pred = best_rf_model.predict(x_test)
r2 = r2_score(y_test, y_pred)
print(f'Coeficiente de Determinación (R²) en el conjunto de prueba: {r2}')

c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Mejores parámetros: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 9, 'n_estimators': 180}
Coeficiente de Determinación (R²) en el conjunto de prueba: 0.6711238480601571

In [47]:
from sklearn.ensemble import RandomForestRegressor

# Crear el modelo de Random Forest
rf_model = RandomForestRegressor(**best_params, random_state=42)  # 100 árboles

# Evaluar múltiples métricas: MSE y R^2
scoring = ['neg_mean_squared_error', 'r2']
scores = cross_validate(rf_model, x, y, cv=5, scoring=scoring, return_train_score=True)

# Obtener y mostrar los resultados
mse_scores = -scores['test_neg_mean_squared_error']
r2_scores = scores['test_r2']

print("MSE scores:", np.mean(mse_scores))
print("R^2 scores:", np.mean(r2_scores))

# Calcular y mostrar RMSE
rmse_scores = np.sqrt(mse_scores)
print("RMSE scores:", rmse_scores)

c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\danan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

MSE scores: 100906.44984887754
R^2 scores: 0.46532770415113045
RMSE scores: [325.5733665  283.89531793 305.67441582 315.44408257 353.54753997]

Modelo final utilizando el mejor R2

In [48]:
import joblib

modelo_final = LinearRegression()

modelo_final.fit(x, y)

# Guardar el modelo entrenado en un archivo
joblib_file = "final_linear_regression_model_int.pkl"
joblib.dump(modelo_final, joblib_file)

print(f"Modelo guardado en {joblib_file}")

Modelo guardado en final_linear_regression_model_int.pkl

In [49]:
modelo_final.coef_

array([[-3.35169576e+01,  1.39753640e+01,  8.80129249e-08,
         8.11433931e-01, -9.11692656e+01, -4.25175777e+01,
        -4.58998564e+01,  1.94707613e+02, -3.33188043e+01,
        -4.97193275e+01,  7.20562653e+01,  3.18646412e+01,
         6.99098110e+01,  4.03611685e+01, -1.39021712e+02,
        -5.33375290e+01,  2.90150069e+01, -5.19959670e+01,
         6.24686993e+01, -8.41679656e+00,  7.46127532e+01,
         2.38258239e+01,  5.25642258e+01,  1.01007527e+02,
        -2.67372598e-02, -1.15091365e-01,  7.39894304e+01,
        -1.23232362e+02, -3.02206645e+02,  7.84510567e+00,
         9.70702594e+02,  2.55174163e+02,  1.66993214e+02,
         1.00395412e+03,  1.12349825e+02,  1.92484512e+02,
         2.33533215e+01,  1.01138203e+03, -1.64006177e+02,
         1.30113555e+02,  2.34846205e+02, -8.91537952e+01,
        -1.77664409e+02, -2.07682498e+02, -1.81298611e+02,
         9.11175519e+02,  4.09253063e+02, -6.64983661e+01,
         2.26244277e+02, -1.21625619e+02, -3.34494777e+02,
         1.93201297e+01, -7.50150303e+01, -2.51472342e+02,
        -1.41421290e+02,  3.61871267e+02,  6.19252645e+02,
        -8.47726835e+01,  3.97192009e+01,  2.68756957e+02,
        -9.06468734e+01, -1.66102898e+02,  3.34969964e+02,
         1.72093992e+02,  2.61187286e+02, -1.64190059e+02,
        -2.38063357e+02, -7.53499775e+00,  8.72201290e+01,
         4.19926592e+01,  2.80245695e+02,  3.49549749e+02,
         5.52252490e+02,  9.04551313e+01, -2.01929535e+02,
        -7.13126805e+02]])

In [50]:
import joblib
import pandas as pd

# Cargar el modelo entrenado desde el archivo
joblib_file = "final_linear_regression_model_int.pkl"
modelo_final = joblib.load(joblib_file)

# Obtener los nombres de las características
feature_names = x.columns

# Obtener los coeficientes (betas) y el intercepto
coeficientes = modelo_final.coef_.flatten()  # Flatten the coefficients array
intercepto = modelo_final.intercept_

# Crear un DataFrame para mostrar los coeficientes con sus correspondientes características
coef_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coeficientes})

print("Intercepto:", intercepto)
print("Coeficientes (betas) y sus correspondientes características:")
print(coef_df)


# Exportar el DataFrame a un archivo CSV
csv_file = "coeficientes_modelo_final.csv"
coef_df.to_csv(csv_file, index=False)

print(f"Coeficientes exportados a {csv_file}")

Intercepto: [420.80101124]
Coeficientes (betas) y sus correspondientes características:
        Feature   Coefficient
0     bathrooms -3.351696e+01
1      bedrooms  1.397536e+01
2     has_photo  8.801292e-08
3   square_feet  8.114339e-01
4            AC -9.116927e+01
..          ...           ...
71     state_VT  3.495497e+02
72     state_WA  5.522525e+02
73     state_WI  9.045513e+01
74     state_WV -2.019295e+02
75     state_WY -7.131268e+02

[76 rows x 2 columns]
Coeficientes exportados a coeficientes_modelo_final.csv